name = "harry "
surname = "khan"
# print(len(name))
# print(name.endswith("rry"))
# print(name.startswith("ha"))
# print(name.capitalize())
# print(name.lower())
# print(name.upper())
print(len(name))
print(name.islower())
print(name.isupper())
print(name.upper())
print(name.lower())
print(name.startswith("h"))
print(name.endswith("y"))
print(name.replace("h", "p"))
print(name + surname)
print(surname.isalnum())
print(surname.isalpha())
print(surname.count("a"))
print(name.capitalize())
str1 = " name "
print(str1.strip())
str2 = "Helloworld"
print()
print()
print(str2.isupper())
print(str2.islower())
print(str2.startswith("H"))
print(str2.endswith("d"))
print(str2.upper())
print(str2.lower())
print(str2.capitalize())
print(str2.replace("H","h"))
